In [168]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.io as pio
import plotly.graph_objects as go
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
from nltk.sentiment.vader import SentimentIntensityAnalyzer
import nltk
import webbrowser
import os
from datetime import datetime
import pytz
import random

In [169]:
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\Shubham\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

True

In [170]:
apps_df = pd.read_csv("Play Store Data.csv")
review_df = pd.read_csv("User Reviews.csv")

In [171]:
apps_df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [172]:
apps_df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

In [173]:
apps_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10841 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

In [174]:
apps_df.describe()

            Rating
count  9367.000000
mean      4.193338
std       0.537431
min       1.000000
25%       4.000000
50%       4.300000
75%       4.500000
max      19.000000

In [175]:
apps_df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
10836    False
10837    False
10838    False
10839    False
10840    False
Length: 10841, dtype: bool

In [176]:
apps_df.isnull()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,False,False,False,False,False,False,False,False,False,False,False,False,False
10837,False,False,False,False,False,False,False,False,False,False,False,False,False
10838,False,False,True,False,False,False,False,False,False,False,False,False,False
10839,False,False,False,False,False,False,False,False,False,False,False,False,False
10840,False,False,False,False,False,False,False,False,False,False,False,False,False

In [177]:
review_df.head()

,App,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
0,10 Best Foods for You,I like eat delicious food. That's I'm cooking ...,Positive,1.00,0.533333
1,10 Best Foods for You,This help eating healthy exercise regular basis,Positive,0.25,0.288462
2,10 Best Foods for You,NaN,NaN,NaN,NaN
3,10 Best Foods for You,Works great especially going grocery store,Positive,0.40,0.875000
4,10 Best Foods for You,Best idea us,Positive,1.00,0.300000

In [178]:
review_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64295 entries, 0 to 64294
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   App                     64295 non-null  object
 1   Translated_Review       37427 non-null  object
 2   Sentiment               37432 non-null  object
 3   Sentiment_Polarity      37432 non-null  float64
 4   Sentiment_Subjectivity  37432 non-null  float64
dtypes: float64(2), object(3)
memory usage: 2.5+ MB

In [179]:
review_df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
64290     True
64291     True
64292     True
64293     True
64294     True
Length: 64295, dtype: bool

In [180]:
review_df.drop_duplicates()

,App,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
0,10 Best Foods for You,I like eat delicious food. That's I'm cooking ...,Positive,1.000000,0.533333
1,10 Best Foods for You,This help eating healthy exercise regular basis,Positive,0.250000,0.288462
2,10 Best Foods for You,NaN,NaN,NaN,NaN
3,10 Best Foods for You,Works great especially going grocery store,Positive,0.400000,0.875000
4,10 Best Foods for You,Best idea us,Positive,1.000000,0.300000
...,...,...,...,...,...
64223,Housing-Real Estate & Property,"If photos posted portal load, fit purpose. I'm...",Positive,0.225000,0.447222
64226,Housing-Real Estate & Property,"Dumb app, I wanted post property rent give opt...",Negative,-0.287500,0.250000
64227,Housing-Real Estate & Property,I property business got link SMS happy perform...,Positive,0.800000,1.000000
64230,Housing-Real Estate & Property,"Useless app, I searched flats kondapur, Hydera...",Negative,-0.316667,0.400000
64236,Houzz Interior Design Ideas,NaN,NaN,NaN,NaN

In [181]:
 # data cleaning
apps_df = apps_df.dropna(subset=["Rating"])
for column in apps_df.columns:
    apps_df[column].fillna(apps_df[column].mode()[0], inplace=True)
apps_df.drop_duplicates(inplace=True)
apps_df=apps_df[apps_df['Rating']<=5]
review_df.dropna(subset=["Translated_Review"], inplace=True)

C:\Windows\Temp\ipykernel_19944\4280260988.py:4: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.

In [182]:
# convert the instails columns to numeric by removing commas and +
apps_df['Installs'] = apps_df['Installs'].str.replace(',','').str.replace('+','').astype(int)

# convert price columns to numeric after remocing $
apps_df['Price'] = apps_df['Price'].str.replace('$','').astype(float)

In [183]:
apps_df.dtypes

App                object
Category           object
Rating            float64
Reviews            object
Size               object
Installs            int64
Type               object
Price             float64
Content Rating     object
Genres             object
Last Updated       object
Current Ver        object
Android Ver        object
dtype: object

In [184]:
# creating the column countrr for task 2
countries = ['United States', 'India', 'Brazil', 'Russia', 'Japan', 'Germany', 'United Kingdom', 'France', 'Italy', 'Canada', 'Australia', 'Spain', 'Mexico', 'Netherlands', 'South Korea', 'Turkey', 'Saudi Arabia', 'Indonesia', 'Sweden', 'Switzerland',]

In [185]:
# data  transformation  
def convert_size(size):
    if 'M' in size:
        return float(size.replace('M',''))
    elif 'K' in size:
        return float(size.replace('K','')) / 1024
    else:
        return np.nan
apps_df['Size'] = apps_df['Size'].apply(convert_size)

In [186]:
apps_df['Size'].unique()

array([ 19. ,  14. ,   8.7,  25. ,   2.8,   5.6,  29. ,  33. ,   3.1,
        28. ,  12. ,  20. ,  21. ,  37. ,   2.7,   5.5,  17. ,  39. ,
        31. ,   4.2,  23. ,   6. ,   6.1,   4.6,   9.2,   5.2,  11. ,
        24. ,   nan,   9.4,  15. ,  10. ,   1.2,  26. ,   8. ,   7.9,
        56. ,  57. ,  35. ,  54. ,   3.6,   5.7,   8.6,   2.4,  27. ,
         2.5,   7. ,  16. ,   3.4,   8.9,   3.9,   2.9,  38. ,  32. ,
         5.4,  18. ,   1.1,   2.2,   4.5,   9.8,  52. ,   9. ,   6.7,
        30. ,   2.6,   7.1,  22. ,   6.4,   3.2,   8.2,   4.9,   9.5,
         5. ,   5.9,  13. ,  73. ,   6.8,   3.5,   4. ,   2.3,   2.1,
        42. ,   9.1,  55. ,   7.3,   6.5,   1.5,   7.5,  51. ,  41. ,
        48. ,   8.5,  46. ,   8.3,   4.3,   4.7,   3.3,  40. ,   7.8,
         8.8,   6.6,   5.1,  61. ,  66. ,   8.4,   3.7,  44. ,   1.6,
         6.2,  53. ,   1.4,   3. ,   7.2,   5.8,   3.8,   9.6,  45. ,
        63. ,  49. ,  77. ,   4.4,  70. ,   9.3,   8.1,  36. ,   6.9,
         7.4,  84. ,  97. ,   2. ,   1.9,   1.8,   5.3,  47. ,  76. ,
         7.6,  59. ,   9.7,  78. ,  72. ,  43. ,   7.7,   6.3,  93. ,
        65. ,  79. , 100. ,  58. ,  50. ,  68. ,  64. ,  34. ,  67. ,
        60. ,  94. ,   9.9,  99. ,  95. ,  80. ,   1.7,  74. ,  62. ,
        69. ,  75. ,  98. ,  85. ,  82. ,  96. ,  87. ,  71. ,  86. ,
        91. ,  81. ,  92. ,  83. ,  88. ,   4.8,   1.3,   4.1,  89. ,
        90. ,   1. ])

In [187]:
# lagromithic 
apps_df['Reviews'] = apps_df['Reviews'].astype(int)
apps_df['Log_Installs']=np.log1p(apps_df["Installs"])
apps_df['Log_Reviews']=np.log1p(apps_df['Reviews'])

In [188]:
def rating_group(rating):
    if rating >= 4:
        return 'Top rated app'
    elif rating >=3:
        return 'Above average app'
    elif rating >=2:
        return 'Average app'
    else:
        return 'Below Average'
apps_df['Rating_Group'] = apps_df['Rating'].apply(rating_group)

In [189]:
# revenue column
apps_df['Revenue'] = apps_df['Price']*apps_df['Installs']

In [190]:
sia = SentimentIntensityAnalyzer()

In [191]:
# Polarity score in SIA
# Postive,Negative,Neutral and Coumpund: -1 - very negative ; +1 -very positive

In [192]:
text = "This app is amazing! I Love the New feature"
sentiment_scores = sia.polarity_scores(text)
print(sentiment_scores)

{'neg': 0.0, 'neu': 0.42, 'pos': 0.58, 'compound': 0.8516}

In [193]:
text2 = 'This app is terrible! I hate the new update and it keeps crashing. '
sentiment_scores = sia.polarity_scores(text2)
print(sentiment_scores)

{'neg': 0.415, 'neu': 0.585, 'pos': 0.0, 'compound': -0.7959}

In [194]:
review_df['Sentiment_Score'] = review_df['Translated_Review'].apply(lambda x: sia.polarity_scores(x)['compound'])

In [195]:
review_df.head()

,App,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity,Sentiment_Score
0,10 Best Foods for You,I like eat delicious food. That's I'm cooking ...,Positive,1.00,0.533333,0.9531
1,10 Best Foods for You,This help eating healthy exercise regular basis,Positive,0.25,0.288462,0.6597
3,10 Best Foods for You,Works great especially going grocery store,Positive,0.40,0.875000,0.6249
4,10 Best Foods for You,Best idea us,Positive,1.00,0.300000,0.6369
5,10 Best Foods for You,Best way,Positive,1.00,0.300000,0.6369

In [196]:
review_df.columns

Index(['App', 'Translated_Review', 'Sentiment', 'Sentiment_Polarity',
       'Sentiment_Subjectivity', 'Sentiment_Score'],
      dtype='object')

In [197]:
apps_df['Last Updated'] = pd.to_datetime(apps_df['Last Updated'],errors='coerce')

In [198]:
apps_df['Year'] = apps_df['Last Updated'].dt.year

In [199]:
apps_df['Category'].unique()

array(['ART_AND_DESIGN', 'AUTO_AND_VEHICLES', 'BEAUTY',
       'BOOKS_AND_REFERENCE', 'BUSINESS', 'COMICS', 'COMMUNICATION',
       'DATING', 'EDUCATION', 'ENTERTAINMENT', 'EVENTS', 'FINANCE',
       'FOOD_AND_DRINK', 'HEALTH_AND_FITNESS', 'HOUSE_AND_HOME',
       'LIBRARIES_AND_DEMO', 'LIFESTYLE', 'GAME', 'FAMILY', 'MEDICAL',
       'SOCIAL', 'SHOPPING', 'PHOTOGRAPHY', 'SPORTS', 'TRAVEL_AND_LOCAL',
       'TOOLS', 'PERSONALIZATION', 'PRODUCTIVITY', 'PARENTING', 'WEATHER',
       'VIDEO_PLAYERS', 'NEWS_AND_MAGAZINES', 'MAPS_AND_NAVIGATION'],
      dtype=object)

In [200]:
apps_df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Log_Installs,Log_Reviews,Rating_Group,Revenue,Year
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19.0,10000,Free,0.0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3 and up,9.210440,5.075174,Top rated app,0.0,2018
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14.0,500000,Free,0.0,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3 and up,13.122365,6.875232,Above average app,0.0,2018
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7,5000000,Free,0.0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3 and up,15.424949,11.379520,Top rated app,0.0,2018
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25.0,50000000,Free,0.0,Teen,Art & Design,2018-06-08,Varies with device,4.2 and up,17.727534,12.281389,Top rated app,0.0,2018
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8,100000,Free,0.0,Everyone,Art & Design;Creativity,2018-06-20,1.1,4.4 and up,11.512935,6.875232,Top rated app,0.0,2018

In [201]:
merged_df = pd.merge(apps_df,review_df,on='App',how='inner')

In [202]:
merged_df['Reviews'] = pd.to_numeric(merged_df['Reviews'], errors='coerce')

In [203]:
merged_df['Last Updated'] = pd.to_datetime(merged_df['Last Updated'], errors='coerce')

In [204]:
merged_df["Revenue"] = merged_df["Installs"] * merged_df["Price"]

In [205]:
merged_df["Country"] = np.random.choice(countries, size=len(merged_df))
merged_df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,...,Log_Reviews,Rating_Group,Revenue,Year,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity,Sentiment_Score,Country
0,Coloring book moana,ART_AND_DESIGN,3.9,967,14.0,500000,Free,0.0,Everyone,Art & Design;Pretend Play,...,6.875232,Above average app,0.0,2018,A kid's excessive ads. The types ads allowed a...,Negative,-0.250,1.000000,-0.2500,Netherlands
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14.0,500000,Free,0.0,Everyone,Art & Design;Pretend Play,...,6.875232,Above average app,0.0,2018,It bad >:(,Negative,-0.725,0.833333,-0.8020,United States
2,Coloring book moana,ART_AND_DESIGN,3.9,967,14.0,500000,Free,0.0,Everyone,Art & Design;Pretend Play,...,6.875232,Above average app,0.0,2018,like,Neutral,0.000,0.000000,0.3612,Turkey
3,Coloring book moana,ART_AND_DESIGN,3.9,967,14.0,500000,Free,0.0,Everyone,Art & Design;Pretend Play,...,6.875232,Above average app,0.0,2018,I love colors inspyering,Positive,0.500,0.600000,0.6369,South Korea
4,Coloring book moana,ART_AND_DESIGN,3.9,967,14.0,500000,Free,0.0,Everyone,Art & Design;Pretend Play,...,6.875232,Above average app,0.0,2018,I hate,Negative,-0.800,0.900000,-0.5719,Brazil

In [206]:
merged_df['Size'] = pd.to_numeric(merged_df['Size'], errors='coerce')

In [207]:
merged_df['Size'].unique()

array([14. , 33. , 39. , 12. , 25. ,  6.1, 11. ,  nan, 24. , 17. ,  2.4,
       27. , 16. ,  2.9, 38. , 21. ,  8.2,  4.2,  5.9, 37. ,  6.8, 10. ,
        2.1, 42. ,  3.9, 18. ,  3.2, 20. , 26. , 48. ,  8.5, 28. , 46. ,
        7.8,  6.6,  5.1,  4. , 32. ,  4.7,  2.7,  7.3, 56. , 29. , 40. ,
        3.1,  5. , 31. ,  8. ,  7.9, 13. ,  7.2, 41. ,  2.8, 15. , 44. ,
        8.1,  4.5,  7.4,  1.9,  1.8,  2.3,  5.2,  1.2,  5.6, 72. ,  9.6,
       23. , 19. , 43. ,  9.5,  8.9, 65. , 22. ,  3.8,  8.4, 58. , 50. ,
       45. , 53. , 68. , 66. , 35. , 76. ,  9.4,  6.9,  4.3, 67. ,  5.5,
        3.3,  3.6,  7.5,  9.1,  8.3,  7. , 77. ,  5.7,  5.3, 30. , 99. ,
       95. , 55. ,  4.4, 36. ,  3. ,  1.7,  7.7, 74. , 97. , 98. ,  4.9,
       52. , 78. , 59. , 85. , 63. , 70. , 49. , 82. , 71. , 73. , 86. ,
       81. , 96. , 57. , 93. , 83. , 60. , 54. , 61. , 75. , 51. , 91. ,
        2.6,  6.4,  1.5, 62. ,  4.1,  9.3,  6.2,  9.7,  8.7, 47. ,  1.6,
        9.8,  6. ,  6.5, 88. ,  4.6,  7.6,  1.3,  2. ,  9.9,  3.5,  7.1,
        9.2,  6.3,  5.4, 92. , 94. ])

In [208]:
fig=px.bar(x=["A","B","C"],y=[1,3,2],title="Sample Bar Chart")
fig.show()

In [209]:
fig.write_html('Intractive_plot.html')

In [210]:
# static visualization : fixed images or plots , non intractive
# intractive Visulization :

In [211]:
html_files_path="./dasboard/"
if not os.path.exists(html_files_path):
    os.makedirs(html_files_path)

In [212]:
plot_containers=""

In [213]:
# Save each Plotly figure to an HTML file
def save_plot_as_html(fig, filename, insight):
    global plot_containers
    filepath = os.path.join(html_files_path, filename)
    html_content = pio.to_html(fig, full_html=False, include_plotlyjs='inline')
    # Append the plot and its insight to plot_containers
    plot_containers += f"""
    <div class="plot-container" id="{filename}" onclick="openPlot('{filename}')">
        <div class="plot">{html_content}</div>
        <div class="insights">{insight}</div>
    </div>
    """
    fig.write_html(filepath, full_html=False, include_plotlyjs='inline')

In [214]:
plot_width = 500
plot_height = 400
plot_bg_color = 'black'
text_color = 'white'
title_font = {'size': 16}
axis_font = {'size': 12}

In [215]:
#Figure 1
category_counts=apps_df['Category'].value_counts().nlargest(10)
fig1=px.bar(
    x=category_counts.index,
    y=category_counts.values,
    labels={'x':'Category','y':'Count'},
    title='Top Categories on Play Store',
    color=category_counts.index,
    color_discrete_sequence=px.colors.sequential.Plasma,
    width=plot_width,
    height=plot_height
)
fig1.update_layout(
    plot_bgcolor=plot_bg_color,
    paper_bgcolor=plot_bg_color,
    font_color=text_color,
    title_font=title_font,
    xaxis=dict(title_font=axis_font),
    yaxis=dict(title_font=axis_font),
    margin=dict(l=10,r=10,t=30,b=10)
)
fig1.update_traces(marker=dict(line=dict(color='white',width=1)))
save_plot_as_html(fig1,"Category Graph 1.html","The top categories on the Play Store are dominated by tools, entertainment, and productivity apps")

In [216]:
#Figure 2
type_counts=apps_df['Type'].value_counts()
fig2=px.pie(
    values=type_counts.values,
    names=type_counts.index,
    title='App Type Distribution',
    color_discrete_sequence=px.colors.sequential.RdBu,
    width=plot_width,
    height=plot_height
)
fig2.update_layout(
    plot_bgcolor=plot_bg_color,
    paper_bgcolor=plot_bg_color,
    font_color=text_color,
    title_font=title_font,
    margin=dict(l=10,r=10,t=30,b=10)
)
#fig1.update_traces(marker=dict(line=dict(color='white',width=1)))
save_plot_as_html(fig2,"Type Graph 2.html","Most apps on the Playstore are free, indicating a strategy to attract users first and monetize through ads or in app purchases")

In [217]:
#Figure 3
fig3=px.histogram(
    apps_df,
    x='Rating',
    nbins=20,
    title='Rating Distribution',
    color_discrete_sequence=['#636EFA'],
    width=plot_width,
    height=plot_height
)
fig3.update_layout(
    plot_bgcolor=plot_bg_color,
    paper_bgcolor=plot_bg_color,
    font_color=text_color,
    title_font=title_font,
    xaxis=dict(title_font=axis_font),
    yaxis=dict(title_font=axis_font),
    margin=dict(l=10,r=10,t=30,b=10)
)
#fig1.update_traces(marker=dict(line=dict(color='white',width=1)))
save_plot_as_html(fig3,"Rating Graph 3.html","Ratings are skewed towards higher values, suggesting that most apps are rated favorably by users")

In [218]:
#Figure 4
sentiment_counts=review_df['Sentiment_Score'].value_counts()
fig4=px.bar(
    x=sentiment_counts.index,
    y=sentiment_counts.values,
    labels={'x':'Sentiment Score','y':'Count'},
    title='Sentiment Distribution',
    color=sentiment_counts.index,
    color_discrete_sequence=px.colors.sequential.RdPu,
    width=plot_width,
    height=plot_height
)
fig4.update_layout(
    plot_bgcolor=plot_bg_color,
    paper_bgcolor=plot_bg_color,
    font_color=text_color,
    title_font=title_font,
    xaxis=dict(title_font=axis_font),
    yaxis=dict(title_font=axis_font),
    margin=dict(l=10,r=10,t=30,b=10)
)
fig4.update_traces(marker=dict(line=dict(color='white',width=1)))
save_plot_as_html(fig4,"Sentiment Graph 4.html","Sentiments in reviews show a mix of positive and negative feedback, with a slight lean towards positive sentiments")

In [219]:
#Figure 5
installs_by_category=apps_df.groupby('Category')['Installs'].sum().nlargest(10)
fig5=px.bar(
    x=installs_by_category.index,
    y=installs_by_category.values,
    orientation='h',
    labels={'x':'Installs','y':'Category'},
    title='Installs by Category',
    color=installs_by_category.index,
    color_discrete_sequence=px.colors.sequential.Blues,
    width=plot_width,
    height=plot_height
)
fig5.update_layout(
    plot_bgcolor=plot_bg_color,
    paper_bgcolor=plot_bg_color,
    font_color=text_color,
    title_font=title_font,
    xaxis=dict(title_font=axis_font),
    yaxis=dict(title_font=axis_font),
    margin=dict(l=10,r=10,t=30,b=10)
)
fig5.update_traces(marker=dict(line=dict(color='white',width=1)))
save_plot_as_html(fig5,"Installs Graph 5.html","The categories with the most installs are social and communication apps, reflecting their broad appeal and daily usage")

In [220]:
# Updates Per Year Plot
updates_per_year = apps_df['Last Updated'].dt.year.value_counts().sort_index()
fig6 = px.line(
    x=updates_per_year.index,
    y=updates_per_year.values,
    labels={'x': 'Year', 'y': 'Number of Updates'},
    title='Number of Updates Over the Years',
    color_discrete_sequence=['#AB63FA'],
    width=plot_width,
    height=plot_height
)
fig6.update_layout(
    plot_bgcolor=plot_bg_color,
    paper_bgcolor=plot_bg_color,
    font_color=text_color,
    title_font=title_font,
    xaxis=dict(title_font=axis_font),
    yaxis=dict(title_font=axis_font),
    margin=dict(l=10, r=10, t=30, b=10)
)
save_plot_as_html(fig6, "Updates Graph 6.html", "Updates have been increasing over the years, showing that developers are actively maintaining and improving their apps.")

In [221]:
#Figure 7
revenue_by_category=apps_df.groupby('Category')['Revenue'].sum().nlargest(10)
fig7=px.bar(
    x=installs_by_category.index,
    y=installs_by_category.values,
    labels={'x':'Category','y':'Revenue'},
    title='Revenue by Category',
    color=installs_by_category.index,
    color_discrete_sequence=px.colors.sequential.Greens,
    width=plot_width,
    height=plot_height
)
fig7.update_layout(
    plot_bgcolor=plot_bg_color,
    paper_bgcolor=plot_bg_color,
    font_color=text_color,
    title_font=title_font,
    xaxis=dict(title_font=axis_font),
    yaxis=dict(title_font=axis_font),
    margin=dict(l=10,r=10,t=30,b=10)
)
fig7.update_traces(marker=dict(line=dict(color='white',width=1)))
save_plot_as_html(fig7,"Revenue Graph 7.html","Categories such as Business and Productivity lead in revenue generation, indicating their monetization potential")

In [222]:
#Figure 8
genre_counts=apps_df['Genres'].str.split(';',expand=True).stack().value_counts().nlargest(10)
fig8=px.bar(
    x=genre_counts.index,
    y=genre_counts.values,
    labels={'x':'Genre','y':'Count'},
    title='Top Genres',
    color=installs_by_category.index,
    color_discrete_sequence=px.colors.sequential.OrRd,
    width=plot_width,
    height=plot_height
)
fig8.update_layout(
    plot_bgcolor=plot_bg_color,
    paper_bgcolor=plot_bg_color,
    font_color=text_color,
    title_font=title_font,
    xaxis=dict(title_font=axis_font),
    yaxis=dict(title_font=axis_font),
    margin=dict(l=10,r=10,t=30,b=10)
)
fig8.update_traces(marker=dict(line=dict(color='white',width=1)))
save_plot_as_html(fig8,"Genre Graph 8.html","Action and Casual genres are the most common, reflecting users' preference for engaging and easy-to-play games")

In [223]:
#Figure 9
fig9=px.scatter(
    apps_df,
    x='Last Updated',
    y='Rating',
    color='Type',
    title='Impact of Last Update on Rating',
    color_discrete_sequence=px.colors.qualitative.Vivid,
    width=plot_width,
    height=plot_height
)
fig9.update_layout(
    plot_bgcolor=plot_bg_color,
    paper_bgcolor=plot_bg_color,
    font_color=text_color,
    title_font=title_font,
    xaxis=dict(title_font=axis_font),
    yaxis=dict(title_font=axis_font),
    margin=dict(l=10,r=10,t=30,b=10)
)
#fig9.update_traces(marker=dict(pattern=dict(line=dict(color='white',width=1))))
save_plot_as_html(fig9,"Update Graph 9.html","The Scatter Plot shows a weak correlation between the last update and ratings, suggesting that more frequent updates dont always result in better ratings.")

In [224]:
#Figure 10
fig10=px.box(
    apps_df,
    x='Type',
    y='Rating',
    color='Type',
    title='Rating for Paid vs Free Apps',
    color_discrete_sequence=px.colors.qualitative.Pastel,
    width=plot_width,
    height=plot_height
)
fig10.update_layout(
    plot_bgcolor=plot_bg_color,
    paper_bgcolor=plot_bg_color,
    font_color=text_color,
    title_font=title_font,
    xaxis=dict(title_font=axis_font),
    yaxis=dict(title_font=axis_font),
    margin=dict(l=10,r=10,t=30,b=10)
)
#fig10.update_traces(marker=dict(pattern=dict(line=dict(color='white',width=1))))
save_plot_as_html(fig10,"Paid Free Graph 10.html","Paid apps generally have higher ratings compared to free apps, suggesting that users expect higher quality from apps they pay for")

In [242]:
# task 1 : Bubble chart : Relation btw app size and rating
# applying the filter
Categories = ['GAME','BEAUTY','BUSINESS','COMICS','COMMUNICATION','DATING','ENTERTAINMENT','SOCIAL','EVENTS']
condition_df = merged_df[(merged_df['Rating'] > 3.5) &  (merged_df['Category'].isin(Categories)) & (merged_df['Reviews'] > 500) & (~merged_df['App'].str.contains('S',case = False, na=False)) & (merged_df['Sentiment_Subjectivity'] > 0.5) & (merged_df['Installs'] > 50000)].copy()
category_translation =  {'BEAUTY':"सौंदर्य",'BUSINESS':'வணிகம்','DATING':'Verabreden'}
condition_df['Translated_Category'] = condition_df['Category'].replace(category_translation)
#time restriction 
ist = pytz.timezone("Asia/Kolkata")
current_time = datetime.now(ist)
#Checking time btw 5pm and 7pm
if 17 <= current_time.hour < 19:
    show_graph = True
else:
    show_graph = False
if show_graph and not condition_df.empty:
    fig11 = px.scatter(
        condition_df,
        x='Size',
        y='Rating',
        size='Installs',
        color='Translated_Category',
        color_discrete_map={"GAME": "#FF69B4"},
        title='App Size vs Rating (Filtered)',
        color_discrete_sequence=px.colors.qualitative.Set2,
        width=plot_width,
        height=plot_height
    )
    
    fig11.update_layout(
        plot_bgcolor='black',
        paper_bgcolor='black',
        font_color='white',
        title_font={'size':16},
        xaxis=dict(title_font={'size':12}),
        yaxis=dict(title_font={'size':12}),
        margin=dict(l=10,r=10,t=30,b=10)
    )
    fig11.update_traces(marker=dict(line=dict(color='white',width=1)))
    save_plot_as_html(fig11, "Size Rating Graph 11.html", "This bubble chart shows the relationship between app size and rating for a filtered subset of apps. Larger bubbles indicate more installs, and colors represent different categories.")
    fig11.show()
else:
    print('Bubble chart is only available between 5 PM and 7 PM IST.')

Bubble chart is only available between 5 PM and 7 PM IST.

In [243]:
# task 2 : filter and map
filter_map_df = merged_df[~merged_df['Category'].str.startswith(('A', 'C', 'G', 'S'), na = False)].copy()
#Category by Installs
Top_categories = (filter_map_df.groupby('Category')['Installs'].sum().sort_values(ascending=False).head(5).index)
filter_map_df = filter_map_df[filter_map_df['Category'].isin(Top_categories)]
#Country by installs
country_installs =  filter_map_df.groupby(['Country','Category'])['Installs'].sum().reset_index()
# Category info
category_info = filter_map_df.groupby('Country')['Category'].agg(lambda x: ', '.join(x.unique())).reset_index()
country_installs = country_installs.merge(category_info, on='Country', how='left')
# highligh > 1M installs
country_installs['Installs_highlight'] = np.where(country_installs['Installs'] > 1000000,'Above 1M','Below 1M')
#time restriction(6PM-8PM)
ist = pytz.timezone("Asia/Kolkata")
current_time = datetime.now(ist)
if 18 <= current_time.hour < 20 :
    show_graph = True
else:
    show_graph = False
if show_graph and not country_installs.empty:
    fig12 = px.choropleth(
        country_installs,
        locations = 'Country',
        locationmode = 'country names',
        color='Installs_highlight',
        hover_name='Country',
        hover_data=['Category_y','Installs'],   
        title="Global Installs by App Category",
        color_discrete_map={
        'Above 1M': 'red',
        'Below 1M': 'blue'
    },
        width=plot_width,
        height=plot_height
    )
    fig12.update_layout(
        plot_bgcolor=plot_bg_color,
        paper_bgcolor=plot_bg_color,
        font_color=text_color,
         margin=dict(l=10,r=10,t=30,b=10)
    )   
    fig12.update_traces(marker=dict(line=dict(color='white',width=1)))
    save_plot_as_html(fig12, "Global Installs Graph 12.html", "This choropleth map visualizes the total installs by country for the top app categories. Countries with more installs are highlighted in brighter colors.")
    fig12.show()
else:
    print('Choropleth map is only available between 6 PM and 8 PM IST.')
    print(country_installs['Installs_highlight'].value_counts())

Choropleth map is only available between 6 PM and 8 PM IST.
Installs_highlight
Above 1M    100
Name: count, dtype: int64

In [244]:
# task 3 :Plot a time series line chart to show the trend of total installs over time.
# adding filter 
filter_time_df = merged_df[(merged_df['Reviews'] > 500) & (~merged_df['App'].str.startswith(('X','Y','Z'), na=False)) & (~merged_df['App'].str.contains('S', case=False, na=False)) & (merged_df['Category'].str.startswith(('E','C','B'), na=False))].copy()
# category Translation
category_translation_2 = {
    "BEAUTY": "सौंदर्य",
    "BUSINESS": "வணிகம்",
    "DATING": "Verabredung",
} 
filter_time_df['Category'] = filter_time_df['Category'].replace(category_translation_2)
#month column
filter_time_df['Last Updated'] = pd.to_datetime(filter_time_df['Last Updated'], errors='coerce')
filter_time_df['Month'] = filter_time_df['Last Updated'].dt.to_period('M').astype(str)
# monthly installs
monthly_installs = filter_time_df.groupby(['Month','Category'])['Installs'].sum().reset_index()
monthly_installs = monthly_installs.sort_values('Month')
# growth percentage
monthly_installs['Growth'] = monthly_installs.groupby('Category')['Installs'].pct_change() 
# time restriction
ist = pytz.timezone("Asia/Kolkata")
current_time = datetime.now(ist)
if 18 <= current_time.hour < 21:
    show_graph = True
else:
    show_graph = False
if show_graph and not monthly_installs.empty:
    fig13 = px.line(
        monthly_installs,
        x='Month',
        y='Installs',
        color='Category',
        title='Monthly Installs Trend by Category',
        color_discrete_sequence=px.colors.qualitative.Set1,
        width=plot_width,
        height=plot_height
    )
    # highlight growth > 20%
    growth_data = monthly_installs[monthly_installs["Growth"] > 0.20]
    for cat in growth_data['Category'].unique():
        temp = growth_data[growth_data['Category'] == cat]

    fig13.add_scatter(
        x=temp['Month'],   
        y=temp['Installs'], 
        fill='tozeroy',
        mode='none',
        opacity=0.2,
        showlegend=False   
    )
    fig13.update_layout(
        plot_bgcolor=plot_bg_color,
        paper_bgcolor=plot_bg_color,
        font_color=text_color,
        title_font=title_font,
        xaxis=dict(title_font=axis_font),
        yaxis=dict(title_font=axis_font),
        margin=dict(l=10,r=10,t=30,b=10)
    )
    fig13.update_traces(marker=dict(line=dict(color='white',width=1)))
    save_plot_as_html(fig13, "Monthly Installs Graph 13.html", "This line chart shows the trend of total installs over time for different categories. It helps identify seasonal patterns and growth trends.")
    fig13.show()
else:
    print('Time series line chart is only available between 6 PM and 9 PM IST.')

Time series line chart is only available between 6 PM and 9 PM IST.

In [245]:
# Task 4 :create a stacked area chart to visualize the cumulative number of installs over time for each app category.
#adding filter
filter_area_df = merged_df[(merged_df['Rating'] >= 4.2) & (~merged_df['App'].str.contains(r'\d', na=False)) & (merged_df['Category'].str.startswith(('T','P'), na = False)) & (merged_df['Reviews'] > 1000) & (merged_df['Size'] >= 20) & (merged_df['Size'] <= 80)].copy()
category_translation_3 = {
    "TRAVEL_AND_LOCAL": "Voyage et Local",
    "PRODUCTIVITY" : "Productividad",
    "PHOTOGRAPHY" : "写真"
}
filter_area_df['Category'] = filter_area_df['Category'].replace(category_translation_3)
# time series 
filter_area_df['Last Updated'] = pd.to_datetime(filter_area_df['Last Updated'], errors='coerce')
filter_area_df['Month'] = filter_area_df['Last Updated'].dt.to_period('M').astype(str)
# monthly_installs
monthly_installs_area = filter_area_df.groupby(['Month','Category'])['Installs'].sum().reset_index()
monthly_installs_area = monthly_installs_area.sort_values(['Category','Month'])
monthly_installs_area['Growth'] = monthly_installs_area.groupby('Category')['Installs'].pct_change()
# Cumulative_Installs
monthly_installs_area['Cumulative_Installs'] = monthly_installs_area.groupby('Category')['Installs'].cumsum()
# time restriction
ist = pytz.timezone("Asia/Kolkata")
current_time = datetime.now(ist)
if 16 <= current_time.hour < 18 :
    show_graph = True
else:
    show_graph = False
if show_graph and not monthly_installs_area.empty:
    # Highlight growth >25% by increasing opacity
     monthly_installs_area["Opacity"] = monthly_installs_area["Growth"].apply(lambda x: 1 if x > 0.25 else 0.5)
     fig14 = px.area(
         monthly_installs_area,
         x="Month",
         y="Cumulative_Installs",
         color="Category",
         title="Cumulative Installs Over Time by App Category",
         
)
     fig14.update_layout(
         plot_bgcolor=plot_bg_color,
        paper_bgcolor=plot_bg_color,
        font_color=text_color,
        title_font=title_font,
        xaxis=dict(title_font=axis_font),
        yaxis=dict(title_font=axis_font),
        margin=dict(l=10,r=10,t=30,b=10)
    )
     fig14.show()
     save_plot_as_html(fig14, "Cumulative Installs Graph 14.html", "This stacked area chart visualizes the cumulative number of installs over time for each app category, highlighting periods of significant growth.")
else:
    print("Stacked area chart is available only between 4 PM and 6 PM IST.")

Stacked area chart is available only between 4 PM and 6 PM IST.

In [246]:
# task 5 : Creating grouped bar chart to compare the average rating and total review count for the top 10 app categories by number of installs
filter_bar_df = merged_df[(merged_df['Rating'] >= 4.0) & (merged_df['Size'] >= 10)].copy()
#January filter
filter_bar_df['Last Updated'] = pd.to_datetime(filter_bar_df['Last Updated'], errors='coerce')
filter_bar_df = filter_bar_df[filter_bar_df['Last Updated'].dt.month == 1]
# Top 10 Categories by installs
Top_categories = (filter_bar_df.groupby('Category')['Installs'].sum().sort_values(ascending=False).head(10).index)
filter_bar_df = filter_bar_df[filter_bar_df['Category'].isin(Top_categories)]
#Rating and Review Matrics
Category_stats = (filter_bar_df.groupby('Category').agg({"Rating": "mean", "Reviews": "sum"})).reset_index()
Category_stats.rename(columns={"Rating" : "Average Rating","Reviews" : "Total Reviews"},inplace= True)
Category_stats = Category_stats.sort_values("Total Reviews", ascending=False)

# time restriction
ist = pytz.timezone("Asia/Kolkata")
current_time = datetime.now(ist)
if 15 <= current_time.hour < 17:
    show_graph = True
else:
    show_graph = False
if show_graph and not Category_stats.empty:
    Category_stats["Total Reviews"] = Category_stats["Total Reviews"] / 1000000
    fig15 = px.bar(
        Category_stats,
        x='Category',
        y=["Average Rating", "Total Reviews"],
        barmode='group',
        title="Average Rating and Total Reviews by Top 10 Categories"
        )
    fig15.update_layout(
           plot_bgcolor=plot_bg_color,
        paper_bgcolor=plot_bg_color,
        font_color=text_color,
        title_font=title_font,
        xaxis=dict(title_font=axis_font),
        yaxis=dict(title_font=axis_font),
        margin=dict(l=10,r=10,t=30,b=10)
        )
    fig15.show()
    save_plot_as_html(fig15, "Rating Reviews Graph 15.html", "This grouped bar chart compares the average rating and total review count for the top 10 app categories by number of installs, providing insights into user engagement and satisfaction.")
else:
    print("Grouped bar chart is available only between 3 PM and 5 PM IST.")

Grouped bar chart is available only between 3 PM and 5 PM IST.

In [247]:
# Task 6:Create a dual-axis chart comparing the average installs and revenue for free vs. paid apps within the top 3 app categories.
# data cleaning
# android ver to numeric
merged_df['Android Ver'] = merged_df['Android Ver'].astype(str)
merged_df['Android Ver'] = (merged_df['Android Ver'].str.extract(r'(\d+\.?\d*)').astype(float))
# adding filter
filter_axis_df = merged_df[(merged_df['Installs'] >= 10000) & (merged_df['Revenue'] >= 10000) & (merged_df['Android Ver'] > 4.0) & (merged_df['Size'] > 15) & (merged_df['Content Rating'] == 'Everyone') & (merged_df['App'].str.len() <= 30)].copy()
Top_categories =(filter_axis_df.groupby('Category')['Installs'].sum().sort_values(ascending=False).head(3).index)
filter_axis_df = filter_axis_df[filter_axis_df['Category'].isin(Top_categories)]
# Free an paid app
Category_stats = (filter_axis_df.groupby('Type').agg({'Installs':'mean','Revenue' : 'sum'}).reset_index())
Category_stats.rename(columns={'Installs':'Average Installs','Revenue':'Total Revenue'},inplace=True)
# time restriction
ist = pytz.timezone("Asia/Kolkata")
current_time = datetime.now(ist)
if 13 <= current_time.hour < 14:
    show_graph = True
else:
    show_graph = False
if show_graph and not Category_stats.empty:
    fig16 = go.Figure()
    # Average installs
    fig16.add_trace(
        go.Bar(
            x=Category_stats['Type'],
            y=Category_stats['Average Installs'],
            name='Average Installs',
            yaxis='y1'
        )
    )
    # Revenue
    fig16.add_trace(
        go.Scatter(
            x=Category_stats['Type'],
            y=Category_stats['Total Revenue'],
            name='Total Revenue',
            yaxis='y2',
            mode='lines+markers'
        )
    )
    fig16.update_layout(
        title="Average Installs vs Revenue (Free vs Paid Apps)",
        xaxis_title="App Type",

        yaxis=dict(
            title="Average Installs",
            side="left"
        ),
        yaxis2=dict(
            title="Revenue ($)",
            overlaying="y",
            side="right"
        ),
        plot_bgcolor=plot_bg_color,
        paper_bgcolor=plot_bg_color,
        font_color=text_color,
        title_font=title_font,
        margin=dict(l=10,r=10,t=30,b=10)
    )
    fig16.show()
    save_plot_as_html(fig16, "Installs Revenue Graph 16.html", "This dual-axis chart compares the average installs and total revenue for free vs. paid apps within the top 3 app categories, highlighting differences in performance and monetization.")
else:
    print("This chart is available only between 1 PM and 2 PM IST.")

In [231]:
plot_containers_split=plot_containers.split('</div>')

In [232]:
if len(plot_containers_split) > 1:
    final_plot=plot_containers_split[-2]+'</div>'
else:
    final_plot=plot_containers

In [233]:
# HTML template for the dashboard
dashboard_html = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Google Play Store Reviews Analytics</title>
    <style>
        body {{
            font-family: Arial, sans-serif;
            background-color: #333;
            color: #fff;
            margin: 0;
            padding: 0;
        }}
        .header {{
            display: flex;
            align-items: center;
            justify-content: center;
            padding: 20px;
            background-color: #444;
        }}
        .header img {{
            margin: 0 10px;
            height: 50px;
        }}
        .container {{
            display: flex;
            flex-wrap: wrap;
            justify-content: center;
            padding: 20px;
        }}
        .plot-container {{
            border: 2px solid #555;
            margin: 10px;
            padding: 10px;
            width: {plot_width}px;
            height: {plot_height}px;
            overflow: hidden;
            position: relative;
            cursor: pointer;
        }}
        .insights {{
            display: none;
            position: absolute;
            right: 10px;
            top: 10px;
            background-color: rgba(0, 0, 0, 0.7);
            padding: 5px;
            border-radius: 5px;
            color: #fff;
        }}
        .plot-container:hover .insights {{
            display: block;
        }}
    </style>
    <script>
        function openPlot(filename) {{
            window.open(filename, '_blank');
        }}
    </script>
</head>
<body>
    <div class="header">
    <img srt="https://www.google.com/imgres?q=google%20log&imgurl=https%3A%2F%2Fmedia.wired.com%2Fphotos%2F5926ffe47034dc5f91bed4e8%2F3%3A2%2Fw_2560%252Cc_limit%2Fgoogle-logo.jpg&imgrefurl=https%3A%2F%2Fwww.wired.com%2F2015%2F09%2Fgoogles-new-logo-trying-really-hard-look-friendly%2F&docid=xcfO8huj4InxHM&tbnid=8FDvkD4JZkRGjM&vet=12ahUKEwjjsaeipKGTAxWvbmwGHUKFAScQnPAOegQIHhAB..i&w=1203&h=802&hcb=2&ved=2ahUKEwjjsaeipKGTAxWvbmwGHUKFAScQnPAOegQIHhAB" alt="Google Logo">
       <h1>Google Play Store Reviews Analytics</h1>
        <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Google_Play_Store_badge_EN.svg/1024px-Google_Play_Store_badge_EN.svg.png" alt="Google Play Store Logo">
    </div>
    <div class="container">
        {plots}
    </div>
</body>
</html>
"""

In [234]:
final_html=dashboard_html.format(plots=plot_containers,plot_width=plot_width,plot_height=plot_height)

In [235]:

dashboard_path=os.path.join(html_files_path,"dashboard.html")

In [236]:
with open(dashboard_path, "w", encoding="utf-8") as f:
    f.write(final_html)

In [237]:
webbrowser.open('file://'+os.path.realpath(dashboard_path))

True